---

version: 2.1

steps: &steps
  steps:
    - checkout

    - restore_cache:
        keys:
          - dependencies-{{ checksum "Gemfile.lock" }}

    - run:
        name: Run CI checks
        command: bin/ci.sh

    - persist_to_workspace:
        root: ./coverage
        paths:
          - "**/.resultset.json"

    - save_cache:
        key: dependencies-{{ checksum "Gemfile.lock" }}
        paths:
          - .bundle

jobs:
  prior-to-prior-to-latest-readline-gcc:
    docker:
      - image: deividrodriguez/byebug:2.3.8-readline-gcc
    <<: *steps

  prior-to-prior-to-latest-libedit-gcc:
    docker:
      - image: deividrodriguez/byebug:2.3.8-libedit-gcc
    <<: *steps

  prior-to-prior-to-latest-readline-clang:
    docker:
      - image: deividrodriguez/byebug:2.3.8-readline-clang
    <<: *steps

  prior-to-prior-to-latest-libedit-clang:
    docker:
      - image: deividrodriguez/byebug:2.3.8-libedit-clang
    <<: *steps

  prior-to-latest-readline-gcc:
    docker:
      - image: deividrodriguez/byebug:2.4.5-readline-gcc
    <<: *steps

  prior-to-latest-libedit-gcc:
    docker:
      - image: deividrodriguez/byebug:2.4.5-libedit-gcc
    <<: *steps

  prior-to-latest-readline-clang:
    docker:
      - image: deividrodriguez/byebug:2.4.5-readline-clang
    <<: *steps

  prior-to-latest-libedit-clang:
    docker:
      - image: deividrodriguez/byebug:2.4.5-libedit-clang
    <<: *steps

  latest-readline-gcc:
    docker:
      - image: deividrodriguez/byebug:2.5.3-readline-gcc
    <<: *steps

  latest-libedit-gcc:
    docker:
      - image: deividrodriguez/byebug:2.5.3-libedit-gcc
    <<: *steps

  latest-readline-clang:
    docker:
      - image: deividrodriguez/byebug:2.5.3-readline-clang
    <<: *steps

  latest-libedit-clang:
    docker:
      - image: deividrodriguez/byebug:2.5.3-libedit-clang
    <<: *steps

  coverage:
    docker:
      - image: deividrodriguez/byebug:2.5.3-readline-clang

    steps:
      - checkout

      - attach_workspace:
          at: ./coverage

      - restore_cache:
          keys:
            - dependencies-{{ checksum "Gemfile.lock" }}

      - run:
          name: Install dependencies
          command: bin/bundle install --jobs 3 --retry 3 --path .bundle

      - save_cache:
          key: dependencies-{{ checksum "Gemfile.lock" }}
          paths:
            - .bundle

      - run:
          name: Upload coverage results to Code Climate
          command: bin/rake coverage:report

      - store_artifacts:
          path: coverage/index.html

  branch-selection:
    docker:
      - image: deividrodriguez/byebug:2.5.3-readline-clang

    steps:
      - run:
          name: Dummy job to select target branches
          command: echo "OK"

workflows:
  version: 2

  test:
    jobs:
      - branch-selection:
          filters:
            branches:
              only: coverage-migration

      - prior-to-prior-to-latest-readline-gcc:
          requires:
            - branch-selection

      - prior-to-prior-to-latest-libedit-gcc:
          requires:
            - branch-selection

      - prior-to-prior-to-latest-readline-clang:
          requires:
            - branch-selection

      - prior-to-prior-to-latest-libedit-clang:
          requires:
            - branch-selection

      - prior-to-latest-readline-gcc:
          requires:
            - branch-selection

      - prior-to-latest-libedit-gcc:
          requires:
            - branch-selection

      - prior-to-latest-readline-clang:
          requires:
            - branch-selection

      - prior-to-latest-libedit-clang:
          requires:
            - branch-selection

      - latest-readline-gcc:
          requires:
            - branch-selection

      - latest-libedit-gcc:
          requires:
            - branch-selection

      - latest-readline-clang:
          requires:
            - branch-selection

      - latest-libedit-clang:
          requires:
            - branch-selection

      - coverage:
          requires:
            - prior-to-prior-to-latest-readline-gcc
            - prior-to-prior-to-latest-libedit-gcc
            - prior-to-prior-to-latest-readline-clang
            - prior-to-prior-to-latest-libedit-clang

            - prior-to-latest-readline-gcc
            - prior-to-latest-libedit-gcc
            - prior-to-latest-readline-clang
            - prior-to-latest-libedit-clang

            - latest-readline-gcc
            - latest-libedit-gcc
            - latest-readline-clang
            - latest-libedit-clang
